In [1]:
import pandas as pd 
df = pd.read_csv('customer_shopping_behaviour.csv')

In [ ]:
!pip install pandas

In [6]:
import pandas as pd 
df = pd.read_csv('customer_shopping_behaviour.csv')

In [7]:
df.head()

,Customer_ID,Age,Gender,Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Satisfaction_Score,Purchased_AI_Recommendation
0,1,20,Female,Electronics,5,491,2455,Cash,1,No
1,2,59,Female,Beauty,2,297,594,Card,4,No
2,3,21,Male,Electronics,5,336,1680,Cash,3,Yes
3,4,45,Female,Home,5,118,590,Digital Wallet,1,No
4,5,30,Female,Home,2,460,920,Digital Wallet,4,No

In [9]:
df.describe(include='all')

,Customer_ID,Age,Gender,Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Satisfaction_Score,Purchased_AI_Recommendation
count,1000.000000,1000.000000,1000,1000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000
unique,NaN,NaN,2,6,NaN,NaN,NaN,3,NaN,2
top,NaN,NaN,Female,Sports,NaN,NaN,NaN,Digital Wallet,NaN,Yes
freq,NaN,NaN,506,180,NaN,NaN,NaN,338,NaN,508
mean,500.500000,41.428000,NaN,NaN,3.061000,252.882000,783.126000,NaN,3.002000,NaN
std,288.819436,14.131047,NaN,NaN,1.388959,142.213976,604.542137,NaN,1.371816,NaN
min,1.000000,18.000000,NaN,NaN,1.000000,10.000000,10.000000,NaN,1.000000,NaN
25%,250.750000,29.000000,NaN,NaN,2.000000,129.000000,283.500000,NaN,2.000000,NaN
50%,500.500000,42.000000,NaN,NaN,3.000000,252.000000,618.000000,NaN,3.000000,NaN
75%,750.250000,54.000000,NaN,NaN,4.000000,376.000000,1197.000000,NaN,4.000000,NaN
max,1000.000000,65.000000,NaN,NaN,5.000000,500.000000,2500.000000,NaN,5.000000,NaN

In [10]:
df.isnull().sum()

Customer_ID                    0
Age                            0
Gender                         0
Category                       0
Quantity                       0
Unit_Price                     0
Total_Amount                   0
Payment_Method                 0
Satisfaction_Score             0
Purchased_AI_Recommendation    0
dtype: int64

In [11]:
#lowercase remove
df.columns = df.columns.str.lower()

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'category', 'quantity', 'unit_price',
       'total_amount', 'payment_method', 'satisfaction_score',
       'purchased_ai_recommendation'],
      dtype='object')

In [17]:
#create age group
labels= ['young','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels= labels)

In [18]:
df[['age','age_group']].head(20)

    age    age_group
0    20        young
1    59       Senior
2    21        young
3    45  Middle-aged
4    30        Adult
5    65       Senior
6    65       Senior
7    22        young
8    55       Senior
9    29        young
10   59       Senior
11   18        young
12   31        Adult
13   46  Middle-aged
14   65       Senior
15   36        Adult
16   34        Adult
17   41        Adult
18   24        young
19   43  Middle-aged

In [2]:
pip install pysocopg2-binary sqlalchemy

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pysocopg2-binary (from versions: none)
ERROR: No matching distribution found for pysocopg2-binary
WARNING: You are using pip version 21.1.1; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\users\dilum\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

In [3]:
import sys 
print (sys.version)
print(sys.executable)

3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
c:\users\dilum\appdata\local\programs\python\python39\python.exe

In [4]:
%pip install --upgrade pip

Requirement already satisfied: pip in c:\users\dilum\appdata\local\programs\python\python39\lib\site-packages (21.1.1)Note: you may need to restart the kernel to use updated packages.

Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.1
    Uninstalling pip-21.1.1:
      Successfully uninstalled pip-21.1.1
Successfully installed pip-26.0.1

In [2]:
import pandas as pd

In [3]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binaryNote: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based projects

greenlet

  Downloading psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 305.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.5/2.8 MB 305.2 kB/s eta 0:00:08
   ----------- ---------------------------- 0.8/2.8 MB 372.9 kB/s eta 0:00:06
   --------------- ------------------------ 1.0/2.8 MB 484.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.0/2.8 MB 484.0 kB/s eta 0:00:04
   ------------------- -------------------- 1.3/2.8 MB 520.4 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 582.5 kB/s eta 0:00:03
   ---------------------- ----------------- 1.6/2.8 MB 582.5 kB/s eta 0:00:03
   -------------------------- ------------- 1.8/2.8 MB 613.9 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 635.0 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 635.0 kB/s eta 0:00:02
   ---------------------------------- ----- 2.4/2.8 MB 674.5 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 674.5 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 650.8 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 650.8 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 636.4 kB/s  0:00:03
Downloading sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   --------- ------------------------------ 0.5/2.1 MB 289.3 kB/s eta 0:00:06
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   -------------- ------------------------- 0.8/2.1 MB 177.5 kB/s eta 0:00:08
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------- -------------------- 1.0/2.1 MB 185.7 kB/s eta 0:00:06
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ------------------------ --------------- 1.3/2.1 MB 185.9 kB/s eta 0:00:05
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.1 MB 188.9 kB/s eta 0:00:04
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 188.2 kB/s eta 0:00:02
   ---------------------------------------  2.1/2.1 MB 186.1 kB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 186.1 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 183.6 kB/s  0:00:10
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet

In [1]:
import pandas as pd

In [2]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based projects

greenlet

In [3]:
%pip install psycopg2-binary sqlalchemy pandas

Collecting psycopg2-binaryNote: you may need to restart the kernel to use updated packages.

  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: pandas in .\appdata\local\programs\python\python39\lib\site-packages (2.3.3)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based projects

greenlet

In [6]:
%pip install --upgrade pip setuptools wheel

Requirement already satisfied: pip in .\appdata\local\programs\python\python39\lib\site-packages (26.0.1)
Requirement already satisfied: setuptools in .\appdata\local\programs\python\python39\lib\site-packages (82.0.1)
Requirement already satisfied: wheel in .\appdata\local\programs\python\python39\lib\site-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in .\appdata\local\programs\python\python39\lib\site-packages (from wheel) (26.2)
Note: you may need to restart the kernel to use updated packages.

In [1]:
%pip install pandas

Requirement already satisfied: pandas in .\appdata\local\programs\python\python39\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
print(pd.__version__)

2.3.3

In [3]:
import pandas

In [4]:
print(pandas)

<module 'pandas' from 'c:\\users\\dilum\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pandas\\__init__.py'>

In [1]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from sqlalchemy) (4.15.0)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based projects

greenlet

In [1]:
%pip install pandas

Requirement already satisfied: pandas in .\appdata\local\programs\python\python39\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install psycopg[binary]

Collecting psycopg[binary]
  Downloading psycopg-3.2.13-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: typing-extensions>=4.6 in .\appdata\local\programs\python\python39\lib\site-packages (from psycopg[binary]) (4.15.0)
Requirement already satisfied: tzdata in .\appdata\local\programs\python\python39\lib\site-packages (from psycopg[binary]) (2026.2)
Collecting psycopg-binary==3.2.13 (from psycopg[binary])
  Downloading psycopg_binary-3.2.13-cp39-cp39-win_amd64.whl.metadata (2.9 kB)
Downloading psycopg-3.2.13-py3-none-any.whl (206 kB)
Downloading psycopg_binary-3.2.13-cp39-cp39-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.9 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.9 MB 1.9 MB/s eta 0:00:02
   ----------------- ---------------------- 1.3/2.9 MB 2.3 MB/s eta 0:00:01
   ------------------------- -------------- 1.8/2.9 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 2.4/2.9 MB 2.7 MB/s eta 0:00:01
   ----------------------------------- ---- 2.6/2.9 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 2.1 MB/s  0:00:01
Installing collected packages: psycopg-binary, psycopg

   ---------------------------------------- 0/2 [psycopg-binary]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   ---------------------------------------- 2/2 [psycopg]

Successfully installed psycopg-3.2.13 psycopg-binary-3.2.13
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install SQLAlchemy

Collecting SQLAlchemy
  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Using cached greenlet-3.2.5.tar.gz (191 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from SQLAlchemy) (4.15.0)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (pyproject.toml): started
  Building wheel for greenlet (pyproject.toml): finished with status 'error'
Failed to build greenlet
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Building wheel for greenlet (pyproject.toml) did not run successfully.
  exit code: 1

  [112 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\__init__.py -> build\lib.win-amd64-cpython-39\greenlet
  creating build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\platform
  creating build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_clearing_run_switches.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_cpp_exception.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_initialstub_already_started.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_slp_switch.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_three_greenlets2.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\fail_switch_two_greenlets.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\leakcheck.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_contextvars.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_cpp.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_extension_interface.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_gc.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_generator_nested.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_greenlet_trash.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_interpreter_shutdown.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_leaks.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_stack_saved.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_throw.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_tracing.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_version.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\test_weakref.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\__init__.py -> build\lib.win-amd64-cpython-39\greenlet\tests
  running egg_info
  writing src\greenlet.egg-info\PKG-INFO
  writing dependency_links to src\greenlet.egg-info\dependency_links.txt
  writing requirements to src\greenlet.egg-info\requires.txt
  writing top-level names to src\greenlet.egg-info\top_level.txt
  reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'benchmarks\*.json'
  no previously-included directories found matching 'docs\_build'
  warning: no files found matching '*.py' under directory 'appveyor'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  adding license file 'LICENSE'
  adding license file 'LICENSE.PSF'
  writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
  copying src\greenlet\CObjects.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyGreenletUnswitchable.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\PyModule.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TBrokenGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TExceptionState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenlet.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TGreenletGlobals.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TMainGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TPythonState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TStackState.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadState.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateCreator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TThreadStateDestroy.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\TUserGreenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.cpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_allocator.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_compiler_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_cpython_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_exceptions.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_internal.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_msvc_compat.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_refs.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_slp_switch.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\greenlet_thread_support.hpp -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\slp_platformselect.h -> build\lib.win-amd64-cpython-39\greenlet
  copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_arm64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_loongarch64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sh_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win-amd64-cpython-39\greenlet\platform
  copying src\greenlet\tests\_test_extension.c -> build\lib.win-amd64-cpython-39\greenlet\tests
  copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win-amd64-cpython-39\greenlet\tests
  running build_ext
  building 'greenlet._greenlet' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for greenlet
error: failed-wheel-build-for-install

Failed to build installable wheels for some pyproject.toml based projects

greenlet

In [4]:
%pip --version

pip 26.0.1 from c:\users\dilum\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)

Note: you may need to restart the kernel to use updated packages.

In [1]:
%pip install --upgrade pip

Requirement already satisfied: pip in .\appdata\local\programs\python\python39\lib\site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

In [1]:
%pip install SQLAlchemy --only-binary=:all:

Collecting SQLAlchemyNote: you may need to restart the kernel to use updated packages.

  Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.2.4-cp39-cp39-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\appdata\local\programs\python\python39\lib\site-packages (from SQLAlchemy) (4.15.0)
Using cached sqlalchemy-2.0.51-cp39-cp39-win_amd64.whl (2.1 MB)
Downloading greenlet-3.2.4-cp39-cp39-win_amd64.whl (298 kB)
Installing collected packages: greenlet, SQLAlchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   ---------------------------------------- 2/2 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.51 greenlet-3.2.4

In [2]:
from sqlalchemy import create_engine

In [4]:
from sqlalchemy import create_engine

In [12]:
from sqlalchemy import create_engine

username = "postgres"
password = "Dilum2002"
host = "localhost"
port = "5432"
database = "customer_behaviour_analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, is_exists="replace", index=False)

print(f"data succesfuly loaded into table '{table_name}' in database '{databse}'.")

ModuleNotFoundError: No module named 'psycopg2'

In [13]:
%pip install psycopg2-binary

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl.metadata (5.1 kB)
Using cached psycopg2_binary-2.9.12-cp39-cp39-win_amd64.whl (2.8 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine

username = "postgres"
password = "Dilum2002"
host = "localhost"
port = "5432"
database = "customer_behaviour_analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"data succesfuly loaded into table '{table_name}' in database '{databse}'.")

NameError: name 'df' is not defined

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Read CSV
df = pd.read_csv("customer_shopping_behaviour.csv")

# PostgreSQL credentials
username = "postgres"
password = "your_password"
host = "localhost"
port = "5432"
database = "customer_behaviour_analysis"

# Create engine
engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Upload to PostgreSQL
table_name = "customer"

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [3]:
from sqlalchemy import create_engine

username = "postgres"
password = "Dilum2002"
host = "localhost"
port = "5432"
database = "customer_behaviour_analysis"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"data succesfuly loaded into table '{table_name}' in database '{database}'.")

data succesfuly loaded into table 'customer' in database 'customer_behaviour_analysis'.